$("#clear").click(function(){
  $("#display").text(" ");
});
$("#zero").click(function(){
$("#display").text($("#display").text()+'0');
});
$("#one").click(function(){
$("#display").text($("#display").text()+'1');
});
$("#two").click(function(){
$("#display").text($("#display").text()+'2');
});
$("#three").click(function(){
$("#display").text($("#display").text()+'3');
});
$("#four").click(function(){
$("#display").text($("#display").text()+'4');
});
$("#five").click(function(){
$("#display").text($("#display").text()+'5');
});
$("#six").click(function(){
$("#display").text($("#display").text()+'6');
});
$("#seven").click(function(){
$("#display").text($("#display").text()+'7');
});
$("#eight").click(function(){
$("#display").text($("#display").text()+'8');
});
$("#nine").click(function(){
$("#display").text($("#display").text()+'9');
});
$("#plus").click(function(){
$("#display").text($("#display").text()+'+');
});
$("#minus").click(function(){
$("#display").text($("#display").text()+'-');
});
$("#division").click(function(){
$("#display").text($("#display").text()+'/');
});
$("#multi").click(function(){
$("#display").text($("#display").text()+'*');
});
$("#equalto").click(function(){
$("#display").text(eval($("#display").text()));
});